In [2]:
import numpy as np

In [3]:
arr = np.arange(10, 100, 10)

In [4]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [5]:
arr[3:5]

array([40, 50])

In [10]:
sliced_arr = arr[3:5]
sliced_arr[:] = 0
arr

array([10, 20, 30,  0,  0, 60, 70, 80, 90])

In [15]:
arr1 = np.arange(10, 100, 10)
sliced_arr1 = arr1[3:5].copy()
sliced_arr1[:] = 0
sliced_arr1

array([0, 0])

In [16]:
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [19]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

In [20]:
arr2d[2, 0]

7

In [22]:
arr2d[2, 1:]

array([8, 9])

In [25]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [27]:
arr2d[:3, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [28]:
arr2d[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [29]:
arr2d[1, :2]

array([4, 5])

In [30]:
arr2d[1:2, :2]

array([[4, 5]])

In [31]:
arr3d = np.array([
        [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
        ],
    
        [
        [11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]
        ],
    
        [
        [20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]
        ],    
])

In [33]:
arr3d.ndim

3

In [34]:
arr3d[0][2, 1:]

array([8, 9])

In [35]:
arr3d[0][:2, :1]

array([[1],
       [4]])