In [1]:
import numpy as np

In [2]:
names = np.array(['Axror', 'Abror', 'Asror', 'Anvar', 'Akmal', 'Axror', 'Asror'])

In [3]:
data = np.random.randn(7, 4)

In [4]:
data

array([[ 0.86719567,  0.98677598,  0.33230864, -1.55918018],
       [-0.27307315,  0.36454984, -1.02515902, -0.44823725],
       [ 0.4061806 , -0.63787689,  0.18472881, -0.13831589],
       [-0.64677993,  1.01776085,  0.44743944,  1.72932322],
       [-0.28878785, -0.96201088, -0.15798632, -0.26613871],
       [-0.17104952,  0.63918472,  0.20308847,  0.15221774],
       [-2.65977076, -1.00464455, -0.46127143, -0.16574032]])

In [5]:
names == 'Axror'

array([ True, False, False, False, False,  True, False])

In [6]:
names == 'Asror'

array([False, False,  True, False, False, False,  True])

In [7]:
data[names == 'Axror']# Axrorga tegishli ma'lumotlar

array([[ 0.86719567,  0.98677598,  0.33230864, -1.55918018],
       [-0.17104952,  0.63918472,  0.20308847,  0.15221774]])

In [22]:
#data[names == 'Asror', :2]

In [21]:
#data[~(names == 'Axror')]

In [18]:
for i in names:
    if i == 'Axror' or i == 'Abror':
        print(data[names == i])

[[ 0.86719567  0.98677598  0.33230864 -1.55918018]
 [-0.17104952  0.63918472  0.20308847  0.15221774]]
[[-0.27307315  0.36454984 -1.02515902 -0.44823725]]
[[ 0.86719567  0.98677598  0.33230864 -1.55918018]
 [-0.17104952  0.63918472  0.20308847  0.15221774]]


In [20]:
data[names == 'Abror']

array([[-0.27307315,  0.36454984, -1.02515902, -0.44823725]])

In [23]:
mask = (names == 'Axror') | (names == 'Abror')
data[mask]

array([[ 0.86719567,  0.98677598,  0.33230864, -1.55918018],
       [-0.27307315,  0.36454984, -1.02515902, -0.44823725],
       [-0.17104952,  0.63918472,  0.20308847,  0.15221774]])

In [24]:
data

array([[ 0.86719567,  0.98677598,  0.33230864, -1.55918018],
       [-0.27307315,  0.36454984, -1.02515902, -0.44823725],
       [ 0.4061806 , -0.63787689,  0.18472881, -0.13831589],
       [-0.64677993,  1.01776085,  0.44743944,  1.72932322],
       [-0.28878785, -0.96201088, -0.15798632, -0.26613871],
       [-0.17104952,  0.63918472,  0.20308847,  0.15221774],
       [-2.65977076, -1.00464455, -0.46127143, -0.16574032]])

In [25]:
data[data<0]

array([-1.55918018, -0.27307315, -1.02515902, -0.44823725, -0.63787689,
       -0.13831589, -0.64677993, -0.28878785, -0.96201088, -0.15798632,
       -0.26613871, -0.17104952, -2.65977076, -1.00464455, -0.46127143,
       -0.16574032])

In [26]:
data[data<0] = 0

data

array([[0.86719567, 0.98677598, 0.33230864, 0.        ],
       [0.        , 0.36454984, 0.        , 0.        ],
       [0.4061806 , 0.        , 0.18472881, 0.        ],
       [0.        , 1.01776085, 0.44743944, 1.72932322],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.63918472, 0.20308847, 0.15221774],
       [0.        , 0.        , 0.        , 0.        ]])

In [43]:
def boolean_slicing():
    """Boolean indekslash yordamida ma'lumotlarni kesib olish """
    data = np.array([[5, 6, 1, 1],
    [9, 1, 1, 1],
    [7, 7, 4, 2],
    [1, 5, 1, 9],
    [9, 9, 4, 5],
    [7, 5, 9, 6],
    [5, 3, 7, 4]])
    ismlar = np.array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
    mask = (ismlar=='Javohir') | (names == 'Elyor')
    return data[mask]

In [44]:
boolean_slicing()

array([[7, 7, 4, 2],
       [1, 5, 1, 9],
       [7, 5, 9, 6],
       [5, 3, 7, 4]])