In [1]:
import numpy as np

In [2]:
arr = np.arange(6).reshape(3, 2)    

In [3]:
arr

array([[0, 1],
       [2, 3],
       [4, 5]])

In [4]:
arr.T

array([[0, 2, 4],
       [1, 3, 5]])

In [5]:
arr.swapaxes

<function ndarray.swapaxes>

In [10]:
arr.swapaxes(1, 0)

array([[0, 2, 4],
       [1, 3, 5]])

In [11]:
np.dot(arr, arr.T)

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])