In [1]:
import numpy as np

In [7]:
arr1 = np.arange(6).reshape(2, 3)
arr2 = np.arange(6, 12).reshape(2, 3)

In [8]:
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
arr2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
arr1 + arr2

array([[ 6,  8, 10],
       [12, 14, 16]])

In [11]:
arr1 * arr2

array([[ 0,  7, 16],
       [27, 40, 55]])

In [12]:
arr2 / arr1

C:\Users\QuadroMi\AppData\Local\Temp\ipykernel_5360\2767132540.py:1: RuntimeWarning: divide by zero encountered in divide
  arr2 / arr1


array([[inf, 7. , 4. ],
       [3. , 2.5, 2.2]])

In [13]:
arr2 - arr1

array([[6, 6, 6],
       [6, 6, 6]])

In [14]:
arr2 ** 2

array([[ 36,  49,  64],
       [ 81, 100, 121]])

In [2]:
#arr2 ** 0.5

In [4]:
import numpy as np
lis = np.arange(6).reshape(2, 3)

In [5]:
lis

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
lis[1, 1:]

array([4, 5])

In [10]:
print("""Men Shamsiddinov MuhammadSodiq Xasanboy o'g'li 2006 - yil 25 - avgustda tug'ilganman va men hozirda klaviaturaga qaramasdan yozishni mashq qilayapman va bu ish juda qiyin ekanu lekin baribir o'rganaman!!!""")

Men Shamsiddinov MuhammadSodiq Xasanboy o'g'li 2006 - yil 25 - avgustda tug'ilganman va men hozirda klaviaturaga qaramasdan yozishni mashq qilayapman va bu ish juda qiyin ekanu lekin baribir o'rganaman!!!
