In [1]:
import numpy as np

In [2]:
data1 = [1, 2.5, 3.5, 6]
arr1 = np.array(data1)

In [3]:
data1

[1, 2.5, 3.5, 6]

In [4]:
arr1

array([1. , 2.5, 3.5, 6. ])

In [5]:
data2 = (4, 5, 3.2, 7)

In [6]:
arr2 = np.array(data2)

In [7]:
data2

(4, 5, 3.2, 7)

In [8]:
arr2

array([4. , 5. , 3.2, 7. ])

In [9]:
arr1.ndim

1

In [10]:
arr2.ndim

1

In [22]:
data3 = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]] #Nested List

In [23]:
arr3 = np.array(data3)

In [24]:
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
arr3.ndim

2

In [29]:
data4 = [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]
arr4 = np.array(data4)

In [30]:
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr4.ndim

2

In [32]:
arr4.shape # Tuple ko'rinishida Qator va ustunlar sonini ko'rsatadi

(3, 3)

In [28]:
arr4.size # Elementlar soni

9

In [36]:
arr5 = np.zeros(shape = (3, 3))
arr5

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
arr6 = np.ones((2, 4))

In [40]:
arr6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
arr7 = np.arange(4, 20, 2) # 4 dan 20 gacha 2 qadam bilan array
arr7

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [44]:
arr8 = np.arange(30)

In [45]:
arr8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])