In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3], dtype = np.float64)
arr1

array([1., 2., 3.])

In [4]:
arr2 = np.array([1,2,3], dtype = np.int32)
arr2

array([1, 2, 3])

In [5]:
arr1.dtype
arr2.dtype

dtype('int32')

In [6]:
arr1.dtype

dtype('float64')

In [7]:
data = np.array([1, 2, 3, 4]) # int64
print(data)
print(data.dtype)

[1 2 3 4]
int32


In [9]:
float_data = data.astype(np.float64)

In [10]:
float_data.dtype

dtype('float64')

In [11]:
data2 = np.array([1.3, 2.7, 5.8, 7])
int_data = data2.astype(np.int64)

In [12]:
int_data

array([1, 2, 5, 7], dtype=int64)