In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.save('data', arr)

In [5]:
arr2 = np.load('data.npy')
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr1 = np.arange(10, 20)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
np.savez('arrays', a = arr, b = arr1)

In [8]:
arrays = np.load('arrays.npz')

In [9]:
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arrays['b']

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
np.savez_compressed('arrays_zip', a = arr, b = arr1)

In [15]:
arr3 = np.load('arrays_zip.npz')

In [16]:
arr3['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr3['b']

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])