In [1]:
import numpy as np

In [2]:
# Massives
arr1 = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
arr2 = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [3]:
#Condition
cond = np.array([True, False, True, True, False])

In [4]:
#where function
result = np.where(cond, arr1, arr2)

In [5]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [6]:
arr = np.random.randn(4, 4)

In [7]:
arr

array([[ 0.29260663, -0.87923411, -0.49230481,  0.62911523],
       [ 0.06371129, -0.05356868,  0.75358109, -0.61943257],
       [-1.38299656,  0.05572227,  2.03889834, -1.37957238],
       [-1.30706375,  0.26161267, -1.74154777, -0.79808405]])

In [8]:
results = np.where(arr>0, 2, -2)
results

array([[ 2, -2, -2,  2],
       [ 2, -2,  2, -2],
       [-2,  2,  2, -2],
       [-2,  2, -2, -2]])