In [1]:
import numpy as np

In [2]:
arr = np.random.randn(5, 4)
arr

array([[ 1.19597128, -1.45256536, -0.33881129,  0.81513587],
       [ 0.44316043, -1.40555836, -0.83868323,  0.28975934],
       [ 1.42184649, -1.72403864,  0.75877563, -0.20870698],
       [-0.94887425,  0.88024438,  0.39675237, -0.03727231],
       [-0.63936727,  1.86135374, -0.44487203,  0.26104833]])

In [3]:
# Barchasini qo'shish
arr.sum()

0.28529814224176986

In [4]:
np.sum(arr)

0.28529814224176986

In [5]:
# Barchasini x o'qi bo'yicha qo'shish Qator Yig'indi
np.sum(arr, axis = 1)

array([ 0.2197305 , -1.51132182,  0.2478765 ,  0.29085019,  1.03816277])

In [6]:
np.sum(arr, axis = 0) # Ustun yig'indi

array([ 1.47273668, -1.84056425, -0.46683854,  1.11996426])

In [10]:
# O'rta arifmetik
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [11]:
data.mean()

2.0

In [12]:
np.mean(data)

2.0

In [13]:
np.mean(arr, axis = 1)

array([ 0.05493262, -0.37783045,  0.06196912,  0.07271255,  0.25954069])

In [14]:
np.mean(arr, axis = 0)

array([ 0.29454734, -0.36811285, -0.09336771,  0.22399285])

In [15]:
# cumsum methodi
data.cumsum()

array([ 0,  1,  3,  6, 10])

In [16]:
np.cumsum(data)

array([ 0,  1,  3,  6, 10])