In [1]:
import numpy as np

In [2]:
arr = np.random.rand(4)

In [3]:
arr

array([0.46323431, 0.88621343, 0.99106715, 0.3994072 ])

In [4]:
sort_arr = np.sort(arr)

In [5]:
sort_arr

array([0.3994072 , 0.46323431, 0.88621343, 0.99106715])

In [6]:
arr.sort()

In [7]:
arr

array([0.3994072 , 0.46323431, 0.88621343, 0.99106715])

In [8]:
arr2d = np.random.randn(2, 4)
arr2d

array([[-0.73169455,  1.42305707, -0.28882246, -0.52362077],
       [ 0.73095378, -0.39350368,  0.16907088, -0.53583385]])

In [9]:
# Vertical Sorting
row_srt = np.sort(arr2d, axis = 0)
row_srt

array([[-0.73169455, -0.39350368, -0.28882246, -0.53583385],
       [ 0.73095378,  1.42305707,  0.16907088, -0.52362077]])

In [10]:
# Horizontal sorting
col_srt = np.sort(arr2d, axis = 1)
col_srt

array([[-0.73169455, -0.52362077, -0.28882246,  1.42305707],
       [-0.53583385, -0.39350368,  0.16907088,  0.73095378]])