In [2]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [4]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [5]:
np.exp(arr) #e asosga ko'ra arr - daraja

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [6]:
np.log(arr) # logarifm e asoska ko'ra arr

C:\Users\QuadroMi\AppData\Local\Temp\ipykernel_3624\2884154507.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr) # logarifm e asoska ko'ra arr


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [7]:
np.log(arr[1:])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [8]:
arr1 = np.random.randn(6)
arr1

array([-0.50437478, -1.5768842 ,  1.12619241,  0.1189305 , -0.50287482,
       -0.61730152])

In [9]:
qoldiq, butun = np.modf(arr1)
print(butun)
print(qoldiq)

[-0. -1.  1.  0. -0. -0.]
[-0.50437478 -0.5768842   0.12619241  0.1189305  -0.50287482 -0.61730152]


In [12]:
np.sign(arr1) # faqat 1 va -1 (ishoraga qarab)

array([-1., -1.,  1.,  1., -1., -1.])

In [13]:
np.isnan(arr1)

array([False, False, False, False, False, False])

In [14]:
arr1[0] = np.NaN
np.isnan(arr1)

array([ True, False, False, False, False, False])

In [15]:
np.abs(arr1)

array([       nan, 1.5768842 , 1.12619241, 0.1189305 , 0.50287482,
       0.61730152])

In [16]:
arr1

array([        nan, -1.5768842 ,  1.12619241,  0.1189305 , -0.50287482,
       -0.61730152])

In [17]:
np.fabs(arr1)

array([       nan, 1.5768842 , 1.12619241, 0.1189305 , 0.50287482,
       0.61730152])

In [18]:
np.ceil(arr1)

array([nan, -1.,  2.,  1., -0., -0.])

In [19]:
np.rint(arr1)

array([nan, -2.,  1.,  0., -1., -1.])

In [20]:
arr1

array([        nan, -1.5768842 ,  1.12619241,  0.1189305 , -0.50287482,
       -0.61730152])

In [21]:
np.rint(arr1)

array([nan, -2.,  1.,  0., -1., -1.])

In [4]:
arr2 = np.random.randn(5)
arr3 = np.random.randn(5)

In [5]:
arr2

array([-0.07082446, -1.63097541, -0.03040501,  0.16500591,  0.50733701])

In [6]:
arr3

array([ 0.8721162 , -0.21098073,  0.5183678 ,  0.11346774, -0.32992216])

In [7]:
np.add(arr2, arr3)

array([ 0.80129174, -1.84195614,  0.48796279,  0.27847365,  0.17741485])

In [8]:
np.multiply(arr2, arr3)

array([-0.06176716,  0.34410438, -0.01576098,  0.01872285, -0.16738172])

In [10]:
np.maximum(arr2, arr3)

array([ 0.8721162 , -0.21098073,  0.5183678 ,  0.16500591,  0.50733701])

In [11]:
np.mod(arr2, arr3)

array([ 0.80129174, -0.15411033,  0.48796279,  0.05153817, -0.15250731])